import sqlite3
from datetime import date
from habit import Habit

# --------------------------------------------------
# Connection Handling
# --------------------------------------------------
def get_db(db_name="main.db"):
    """
    Create and return a SQLite database connection.
    Enables foreign key constraints.
    """
    db=sqlite3.connect(db_name)
    db.execute("PRAGMA foreign_keys = ON")
    return db

# --------------------------------------------------
# Table Creation
# --------------------------------------------------
def create_tables(db):
    """
    Create required tables if they do not exist.
    """
    cur = db.cursor()

    cur.execute("""
    CREATE TABLE IF NOT EXISTS habits (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT UNIQUE,
        periodicity TEXT,
        start_date TEXT
    )
    """)

    cur.execute("""
    CREATE TABLE IF NOT EXISTS completions (
        habit_id INTEGER,
        completion_date TEXT,
        FOREIGN KEY (habit_id) REFERENCES habits(id) ON DELETE CASCADE
    )
    """)

    db.commit()

# --------------------------------------------------
# Save Operations
# --------------------------------------------------
def save_habit(db, habit):
    """
    Save a new habit into the database.
    The ID is automatically generated by SQLite.
    """

    cur = db.cursor()

    cur.execute("""
        INSERT INTO habits (name, periodicity, start_date)
        VALUES (?, ?, ?)
    """, (habit.name, habit.periodicity, habit.start_date.isoformat()))

    habit.id = cur.lastrowid
    db.commit()

def save_completion(db, habit_id, completion_date):
    """
    Save a completion record for a habit.
    """
    cur = db.cursor()
    cur.execute("""
        INSERT INTO completions (habit_id, completion_date)
        VALUES (?, ?)
    """, (habit_id, completion_date.isoformat()))

    db.commit()

def save_habits(db, habits):
    """
    Save a list of habits and completions.
    """
    create_tables(db)

    for habit in habits:
        save_habit(db, habit)
        for completion in habit.completions:
            save_completion(db, habit.id, completion)

    db.commit()


# --------------------------------------------------
# Load Operations
# --------------------------------------------------
def load_habits(db):
    """
    Load all habits and their completions from the database.
    Returns a list of Habit objects.
    """
    cur = db.cursor()
    cur.execute("SELECT * FROM habits")
    habits_data = cur.fetchall()

    habits = []

    for h in habits_data:
        habit = Habit(h[0], h[1], h[2], date.fromisoformat(h[3]))
        # Load completions
        cur.execute(
            "SELECT completion_date FROM completions WHERE habit_id=?",
            (h[0],)
        )

        habit.completions = [
            date.fromisoformat(r[0]) for r in cur.fetchall()
        ]

        habits.append(habit)

    return habits

# --------------------------------------------------
# Update Operations
# --------------------------------------------------

def update_habit(db, habit_id, new_name=None, new_periodicity=None):
    """
    Update habit name and/or periodicity.

    Args:
        db: Database connection
        habit_id (int): ID of habit to update
        new_name (str): Optional new name
        new_periodicity (str): Optional new periodicity ('daily' or 'weekly')

    Raises:
        ValueError: If periodicity invalid
    """
    cur = db.cursor()

    if new_periodicity and new_periodicity not in {"daily", "weekly"}:
        raise ValueError("periodicity must be 'daily' or 'weekly'")

    if new_name and new_periodicity:
        cur.execute("""
            UPDATE habits
            SET name=?, periodicity=?
            WHERE id=?
        """, (new_name, new_periodicity, habit_id))

    elif new_name:
        cur.execute("""
            UPDATE habits
            SET name=?
            WHERE id=?
        """, (new_name, habit_id))

    elif new_periodicity:
        cur.execute("""
            UPDATE habits
            SET periodicity=?
            WHERE id=?
        """, (new_periodicity, habit_id))

    db.commit()

# --------------------------------------------------
# Delete Operations
# --------------------------------------------------

def delete_habit(db, habit_id):
    """
    Delete a habit and all its completions from the database.

    Args:
        db: Database connection
        habit_id (int): ID of habit to delete
    """

    cur = db.cursor()

    # Delete related completions first (foreign key dependency)
    cur.execute(
        "DELETE FROM completions WHERE habit_id=?",
        (habit_id,)
    )

    # Delete habit itself
    cur.execute(
        "DELETE FROM habits WHERE id=?",
        (habit_id,)
    )

    db.commit()
