import sqlite3
from datetime import date
from habit import Habit

# --------------------------------------------------
# Connection Handling
# --------------------------------------------------
def get_db(db_name="main.db"):
    """
    Create and return a SQLite database connection.
    Enables foreign key constraints.
    """
    db=sqlite3.connect(db_name)
    return db

# --------------------------------------------------
# Table Creation
# --------------------------------------------------
def create_tables(db):
    """
    Create required tables if they do not exist.
    """
    cur = db.cursor()

    cur.execute("""
    CREATE TABLE IF NOT EXISTS habits (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT UNIQUE,
        periodicity TEXT,
        start_date TEXT
    )
    """)

    cur.execute("""
    CREATE TABLE IF NOT EXISTS completions (
        habit_id INTEGER,
        completion_date TEXT,
        FOREIGN KEY (habit_id) REFERENCES habits(id)
    )
    """)

    db.commit()

# --------------------------------------------------
# Save Operations
# --------------------------------------------------
def save_habit(db, habit):
    """
    Save a new habit into the database.
    The ID is automatically generated by SQLite.
    """

    cur = db.cursor()

    cur.execute("""
        INSERT INTO habits (name, periodicity, start_date)
        VALUES (?, ?, ?)
    """, (habit.name, habit.periodicity, habit.start_date.isoformat()))

    habit.id = cur.lastrowid
    db.commit()

def save_completion(db, habit_id, completion_date):
    """
    Save a completion record for a habit.
    """
    cur = db.cursor()
    cur.execute("""
        INSERT INTO completions (habit_id, completion_date)
        VALUES (?, ?)
    """, (habit_id, completion_date.isoformat()))

    db.commit()

def save_habits(db, habits):
    """
    Save a list of habits and completions.
    """
    create_tables(db)

    for habit in habits:
        save_habit(db, habit)
        for completion in habit.completions:
            save_completion(db, habit.id, completion)

    db.commit()


# --------------------------------------------------
# Load Operations
# --------------------------------------------------
def load_habits(db):
    """
    Load all habits and their completions from the database.
    Returns a list of Habit objects.
    """
    cur = db.cursor()
    cur.execute("SELECT * FROM habits")
    habits_data = cur.fetchall()

    habits = []

    for h in habits_data:
        habit = Habit(h[0], h[1], h[2], date.fromisoformat(h[3]))
        # Load completions
        cur.execute(
            "SELECT completion_date FROM completions WHERE habit_id=?",
            (h[0],)
        )

        habit.completions = [
            date.fromisoformat(r[0]) for r in cur.fetchall()
        ]

        habits.append(habit)

    return habits

